### ISSUE TITLE
Automatically blit the screen, handle events, and pause

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#10]
It might be a good idea to restructure Slither a bit so that it can automatically blit the screen and pause.
For example, the main loop in turnAndMove.py

``` python
continueLoop = True
while continueLoop:
    slither.blit(screen) # Display
    snakey.changeXBy(1)
    snakey.changeDirectionBy(1)
    # Handle quitting
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            continueLoop = False
    time.sleep(0.01)
```

Could be written as

``` python
def run_a_frame():
    snakey.changeXBy(1)
    snakey.changeDirectionBy(1)
def handle_quit():
    return True # A return value of true means to exit
slither.setQuitCallback(handle_quit)
slither.runMainloop(run_a_frame)
```

This would make Slither even easier to use.

**Comment by Tymewalk** [comment]
How would `runMainLoop` look in `slither/__init__.py`? Or is that just how Python modules work?

**Comment by BookOwl** [comment]
Probably something like

``` python
def runMainLoop(frameFunc):
    while True:
        blit(screen) # screen could either be a global variable, or passed in
        frameFunc()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                if runQuitCallback():
                    # runQuitCallback would run the function
                    # given to setQuitCallback, and return its result
                    break
            else:
                eventCallbacks[event.type](event)
                # eventCallbacks would be a dictionary mapping
                # event types to handler functions.
        time.sleep(0.01)
```

It would require a rather large restructuring of your code (which is fine as it is, by the way).
I could code it up and make a pull request.

**Comment by Tymewalk** [comment]
@BookOwl That sounds good, thanks! :smile: In the meantime I'll work on some of the other issues.

**Comment by Tymewalk** [comment]
Wait, actually, I might be able to just drop the code into `__init__` and then sort out the tests myself.
Other than the tests, nothing else has to be rewritten, right?

**Comment by BookOwl** [comment]
@Tymewalk You would still have to code the callback registering functions. I'm working on it right now, I should finish soon

**Comment by Tymewalk** [comment]
@BookOwl Thanks a lot, this'll really help! I'll make sure to credit you for the code.

**Comment by Tymewalk** [comment]
#14 was merged, so I'm going to close this.
