### ISSUE TITLE
Release on PyPi?

### ISSUE THREAD

**Issue by ghost** [Tymewalk/Slither#13]
It would be much easier if you submitted Slither to PyPi? Then you could just type "pip install slither" and you've got it. Anyways, I found a guide on submitting packages to PyPi here:

**Comment by ghost** [comment]
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by Tymewalk** [comment]
Sounds good to me, I've submitted stuff to PyPi before. The only problem might be PyGame, is that up on PyPi as well?

**Comment by BookOwl** [comment]
@Tymewalk unfortunately, it isn't. You could just not list it in your dependencies and tell users to install it from the Pygame website before they use Slither

**Comment by Tymewalk** [comment]
@BookOwl All right. I'll see if I can get a setup.py working for Slither.
I can probably just copy-paste it from Tymeventure with a couple of changes :stuck_out_tongue_closed_eyes:

**Comment by Tymewalk** [comment]
By the way, #17 will have to be resolved before this can be finished.

**Comment by BookOwl** [comment]
I think we're ready

**Comment by Tymewalk** [comment]
@BookOwl I think so too. What version do we release as? 0.0.1?

**Comment by BookOwl** [comment]
I would do 0.1.0

**Comment by Tymewalk** [comment]
@BookOwl All right. (I'll also make a release here on GitHub.)
How do we share a development version/fix over PyPi? Or is that discouraged?

**Comment by Tymewalk** [comment]
We're now released on PyPi as `slither`. Yay!

**Comment by BookOwl** [comment]
1. I don't think that development versions are supposed to be shared on pypi. You do put up bug fixes.
2. Great! I'll test it out when I get home

**Comment by ghost** [comment]
YAY! Finally an easy way to get slither

**Comment by BookOwl** [comment]
Should we close this?

**Comment by Tymewalk** [comment]
@BookOwl That depends. Does it work for you?

**Comment by BookOwl** [comment]
Pip install is not working for me.

```
pip install slither
Collecting slither
  Could not find a version that satisfies the requirement slither (from versions: )
No matching distribution found for slither
```

I tried it on two different Windows machines

**Comment by Tymewalk** [comment]
@BookOwl Weird... I know it's up on PyPi.

**Comment by BookOwl** [comment]
@Tymewalk, can you give me the URL?

**Comment by Tymewalk** [comment]
@BookOwl Yeah. Just give me a moment, it's under `slither` if that helps.

**Comment by Tymewalk** [comment]
https://pypi.python.org/pypi/slither

**Comment by BookOwl** [comment]
It doesn't look like you have any files uploaded...
Can you give me access to the Pypi thing so that I can see what's wrong?

**Comment by Tymewalk** [comment]
> It doesn't look like you have any files uploaded...

Strange... I know I have slither and Tymeventure up there.

**Comment by Tymewalk** [comment]
@BookOwl WAIT - I found it. There's information, but no files. I never uploaded any. :facepunch: (closest thing to facepalm)

**Comment by Tymewalk** [comment]
```
running sdist
running egg_info
creating slither.egg-info
writing slither.egg-info/PKG-INFO
writing top-level names to slither.egg-info/top_level.txt
writing dependency_links to slither.egg-info/dependency_links.txt
writing manifest file 'slither.egg-info/SOURCES.txt'
reading manifest file 'slither.egg-info/SOURCES.txt'
writing manifest file 'slither.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating slither-0.1.0
creating slither-0.1.0/slither
creating slither-0.1.0/slither.egg-info
making hard links in slither-0.1.0...
hard linking setup.py -> slither-0.1.0
hard linking slither/__init__.py -> slither-0.1.0/slither
hard linking slither/snakey.png -> slither-0.1.0/slither
hard linking slither.egg-info/PKG-INFO -> slither-0.1.0/slither.egg-info
hard linking slither.egg-info/SOURCES.txt -> slither-0.1.0/slither.egg-info
hard linking slither.egg-info/dependency_links.txt -> slither-0.1.0/slither.egg-info
hard linking slither.egg-info/top_level.txt -> slither-0.1.0/slither.egg-info
Writing slither-0.1.0/setup.cfg
creating dist
Creating tar archive
removing 'slither-0.1.0' (and everything under it)
running upload
Submitting dist/slither-0.1.0.tar.gz to https://pypi.python.org/pypi
Server response (200): OK
```

That's what `python setup.py sdist upload -r pypi` gives me. Let's check to see what files are up on PyPi now...

**Comment by Tymewalk** [comment]
@BookOwl Now try.

**Comment by BookOwl** [comment]
It worked!

**Comment by Tymewalk** [comment]
@BookOwl Yay, it finally works!
So, TL;DR: **You can use `pip install slither`, and Tymewalk needs to learn register != upload.**

**Comment by Tymewalk** [comment]
Oh, and we completed all the April 9th tasks!
