### ISSUE TITLE
Example folder?

### ISSUE THREAD

**Issue by ghost** [Tymewalk/Slither#16]
Stuff the current examples in a folder, make some more. Simple. I found examples really helped me when learning python, it lets you understand how to use the code to make stuff.

**Comment by ghost** [comment]
I'll work on making more examples. Just downloading the latest release of slither...

**Comment by Tymewalk** [comment]
Sounds good, but how do I import Slither if it's a folder up from the Python programs?
Or should I get a setup.py file so I can just install it?

**Comment by ghost** [comment]
No need, found out how: http://stackoverflow.com/questions/4383571/importing-files-from-different-folder-in-python

import sys
sys.path.insert(0, '/slither')

import slither

I'll test this...

**Comment by Omegabyte** [comment]
Doesn't work, trying another method...

**Comment by ghost** [comment]
Ok the method works but only imports as **init**

**Comment by ghost** [comment]
Found a solution, add a copy of slither inside the slither folder named slither.

**Comment by Tymewalk** [comment]
Then what about:

```
import sys
sys.path.insert(0, '/')

import slither
```

Also, copying Slither inside the examples folder is a bad idea - it can lead to problems such as the two versions being different.

**Comment by ghost** [comment]
Ok I'll try that.

**Comment by ghost** [comment]
Nope "No module named slither"

**Comment by ghost** [comment]
What I meant was make another init inside the slither folder but name it slither.

**Comment by Tymewalk** [comment]
Hmm... what if I put this in `slither/slither.py`:

```
from __init__ import *
```

**Comment by ghost** [comment]
Good idea!

**Comment by ghost** [comment]
Still getting errors  -_-
Import init somehow works fine

**Comment by ghost** [comment]
tried **_import init as slither**_ but it failed

**Comment by ghost** [comment]
Just wait till the PyPi release I guess? Since that would install slither into lib or site-packages or somewhere.

**Comment by Tymewalk** [comment]
@Omegabyte Or until #17 gets fixed, which would also work.

**Comment by ghost** [comment]
I changed the installation instructions, if you follow the instructions you should be able to import slither from anywhere, this allows for an example folder.
b87bd64

**Comment by Tymewalk** [comment]
@Omegabyte Sounds good! This will work as a temporary fix for now.
I'd really prefer to get a `setup.py` working (in #17), but for now this will do.
I'm re-cloning the repo so I can make the examples folder.

**Comment by Tymewalk** [comment]
The commit I just commented on fixes this issue.
