### ISSUE TITLE
setup.py?

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#17]
There needs to be a proper setup.py file.

**Comment by ghost** [comment]
What do you mean?

**Comment by Tymewalk** [comment]
A setup.py file can be used to install Slither onto people's machines. It's necessary to have one to upload to PyPi. Plus, people could then just type `import slither` when they want to use it.

**Comment by BookOwl** [comment]
Should I work on this?

**Comment by Tymewalk** [comment]
@BookOwl No, I can probably set it up myself.
I plan to just copy-paste the one from Tymeventure and reformat it for Slither :stuck_out_tongue:

**Comment by BookOwl** [comment]
Just make sure that snakey.png is added to the packages produced

**Comment by Tymewalk** [comment]
@BookOwl Oh, yeah. How should I do that with a `setup.py` file?

**Comment by BookOwl** [comment]
I'm pretty sure that you use `package_data`, but I'm not sure. I've never had to do that before

**Comment by Tymewalk** [comment]
@BookOwl I'll take a look at it now. In the meantime I'll at least add the `setup.py` file.

**Comment by ghost** [comment]
setup.py Doesn't work, it just makes an egg file in site packages and gives projects import error.

**Comment by Tymewalk** [comment]
@Omegabyte You need to use `python setup.py build` and then `python setup.py install`.

**Comment by ghost** [comment]
> python setup.py build

 Didn't do anything, still got an egg file.

**Comment by Omegabyte** [comment]
I changed the installation instructions to move the slither folder to python's lib folder, this allows you to import slither from anywhere.

**Comment by Tymewalk** [comment]
@Omegabyte Did you also run `python setup.py install`? `build` only makes the egg files so they can be installed.

**Comment by Tymewalk** [comment]
Wait, I ran `python setup.py build; python setup.py install`, but I can't use Slither. Hm...

**Comment by ghost** [comment]
> python setup.py install

Might be the problem. It just copies and pastes the egg file.

**Comment by Tymewalk** [comment]
`setup.py` has been added, and I've gotten it to work with these methods.
Continue any other problems on #27.
