### ISSUE TITLE
Necessary looks blocks

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#2]
These looks blocks from Scratch should be added in:
- [x] Switch to costume by number
- [x] Switch to costume by name
- [x] Default costume for tests
- [x] Add costume
- [x] Delete costume
- [x] Change size by ()
- [x] Set size to ()
- [x] Show
- [x] Hide
- [x] Z-indexing
- [x] Get costume number
- [x] Get size
- [x] Get costume name

Let me know of any more that might be needed, or any that should be removed.

**Comment by Tymewalk** [comment]
Added some of the reporters.

**Comment by Tymewalk** [comment]
Size functions now work properly with the basic test. Run it for yourself.

**Comment by Tymewalk** [comment]
The costumes now work with both name and numbers, as the commits in #3 show. Pretty soon I should be able to get a `deleteCostume()` function working.

**Comment by Tymewalk** [comment]
Deleting costumes has been added.
Also, show and hide were unchecked but I added them in now.

**Comment by Tymewalk** [comment]
I added in the last few items in #3's latest commit, so I'm gonna go merge that now.

**Comment by Tymewalk** [comment]
Here's the updates on the last 4 items:
- Default costume was added.
- Next costume is not needed because it can be workarounded for now.
- The layer blocks are staying until I get feedback on what to do with them.

**Comment by ghost** [comment]
Hmm, layers. How big should a layer be? How many layers? Why so many questions!?!?

**Comment by Tymewalk** [comment]
@Omegabyte  Layering of sprites works like it does in Scratch - one sprite on top of another.
I think the simplest way is to reorder the `sprites` list.

**Comment by Tymewalk** [comment]
OK, so here's what we've narrowed this down to:
- The last two things are layers
- Layering is done by re-ordering the sprites list

**Comment by Tymewalk** [comment]
Based on the conclusion we reached in #26, I'm replacing layers with z-indexes.

**Comment by Tymewalk** [comment]
#31 fixes the final item - the z-indexes.
I can now close this.
It feels good.
