### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#22]
It would be cool to have a logo. Snakey could be our mascot.

**Comment by BookOwl** [comment]
I made one! :D
![logo](https://cloud.githubusercontent.com/assets/13385064/14028163/82c374ea-f1d1-11e5-84b7-8ebc442b2d70.png)
@Tymewalk what do you think of it?

**Comment by Tymewalk** [comment]
@BookOwl If I could +1 more than once I would.
I'll use this on the Scratch topic and in README.md (with credit to you, of course :smile:).
(Snakey is already the mascot BTW)
What fonts did you use?

**Comment by BookOwl** [comment]
Thanks! :DI used Segoe Script for the Slither text. I can't remember what font I used for the main text.

**Comment by ghost** [comment]
Nice logo!

**Comment by BookOwl** [comment]
@Tymewalk

**Comment by Tymewalk** [comment]
@BookOwl Yeah?

**Comment by BookOwl** [comment]
@Tymewalk are you going to use the logo?

**Comment by Tymewalk** [comment]
It just occurred to me that we should also have a square logo, for our new orginization (#37).

**Comment by BookOwl** [comment]
Snakey with a green background?

**Comment by Tymewalk** [comment]
@BookOwl That should be OK. Do you want me to make it? It shouldn't be that hard.

**Comment by BookOwl** [comment]
@Tymewalk OK

**Comment by Tymewalk** [comment]
Reopening since work is being done here.

**Comment by Tymewalk** [comment]
![128x128 logo](http://i.cubeupload.com/PhV2bQ.png)
How's this?

**Comment by BookOwl** [comment]
Looks ~~good~~ great, but maybe you should add the word "Slither" to the top or bottom of it using the Segoe Script font (to be consistent)

**Comment by Tymewalk** [comment]
@BookOwl I don't have that font. Where can I get it?

**Comment by BookOwl** [comment]
I don't know, it came with my windows laptop.

**Comment by Tymewalk** [comment]
@BookOwl Oh well. (I'm on Linux, so I guess it might be a Windows-exclusive.)
![new logo](http://i.cubeupload.com/a7wxYu.png)
I used the text from your banner and added it on here. How does it look?

**Comment by BookOwl** [comment]
Looks good to me!

**Comment by BookOwl** [comment]
apparently, the segoe font is owned by microsoft. o_0

**Comment by Tymewalk** [comment]
@BookOwl In that case I'll change our organization's profile pic and close the issue.

**Comment by BookOwl** [comment]
@Tymewalk, do you think that it would be a good idea to put our banner logo on the Scratch topic?

**Comment by Tymewalk** [comment]
@BookOwl Yep. I'll upload it to CubeUpload in a moment.

**Comment by Tymewalk** [comment]
Done, check the Slither topic: https://scratch.mit.edu/discuss/topic/187865/?page=1#post-1845049
(Apparently 43 minutes is a moment :stuck_out_tongue:)
