### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#24]
Adding sound support would be great! I think that it would be best to implement it as a Sound class that wraps the Pygame sound API.

Relevent docs: http://www.pygame.org/docs/ref/music.html

**Comment by Tymewalk** [comment]
Sounds perfect! Would `pygame.mixer` work?
EDIT: Never mind, it turns out that's what's being used :stuck_out_tongue_closed_eyes:

**Comment by BookOwl** [comment]
@Omegabyte implemented sounds using a loadSound function. I think that it would be better to use a Sound class to be more consistent with the rest of the API. @Tymewalk what do you think?

**Comment by ghost** [comment]
Ok, I'll add a sound class.

**Comment by ghost** [comment]
ARGHHHH Everything's gone haywire.

**Comment by BookOwl** [comment]
What happened?

**Comment by ghost** [comment]
For my test it says I entered two arguments when I only entered 1.

**Comment by ghost** [comment]
TypeError: loadSound() takes exactly 1 argument (2 given)

**Comment by BookOwl** [comment]
Since it is your loadSound function is in a class, Python automatically passes the class instance as the first argument. I would just take it out of the class.

**Comment by ghost** [comment]
OH, I get whats happening now, I forgot to add self as an argument. LOL

**Comment by ghost** [comment]
Ok, the the only problem is #28. Once it's fixed I'll start a pull request.

**Comment by ghost** [comment]
Merged sound branch. SLITHER NOW HAS SOUNDS!!!!

**Comment by BookOwl** [comment]
~~We should be using pygame.mixer.music, since that supports more formats (like MP3 and OGG)~~
nvm
