### ISSUE TITLE
Using Codacy?

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#25]
[Codacy](https://www.codacy.com) is an online code review tool. Basically, it makes sure that we write good, quality code. It is also free for open source projects (like us). Currently, it gives us an A.

[![Codacy Badge](https://api.codacy.com/project/badge/grade/6c21312189334c1782a49e152d0f4b78)](https://www.codacy.com/app/stanleybookowl/Slither)

Should we use it?

**Comment by Tymewalk** [comment]
How does it detect things like "Unused Code" and "Code Style"?

**Comment by BookOwl** [comment]
I don't know, but it does a good job. I use it for some of my projects.

**Comment by Tymewalk** [comment]
All right, it looks good to me! (Now we'll have something to tell us when we've broken the entire thing :stuck_out_tongue:)
@Omegabyte, what's your take on this?

**Comment by ghost** [comment]
Seems good but what does it consider as 'good quality code'?

**Comment by Tymewalk** [comment]
@BookOwl Why'd you close it?

**Comment by Tymewalk** [comment]
Bump. I don't remember us reaching any decisions.

**Comment by Tymewalk** [comment]
Since this is open, I think Codacy is a great idea. I already see a couple places where it says there's code that isn't being used (a couple `import pygame`s where Slither just takes care of that for us, for example).

**Comment by Tymewalk** [comment]
@Omegabyte I think it considers it based on things like how many TODOs we have, and how much code goes unused.

**Comment by BookOwl** [comment]
@Tymewalk, do you think we should use it?

**Comment by Tymewalk** [comment]
@BookOwl Yes. I already see a few things on Codacy that could be fixed before they cause bigger problems later on.

**Comment by BookOwl** [comment]
OK, I'll put the icon on the README and close this.
