### ISSUE TITLE
Layers - reordering or z-index?

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#26]
(For the last two tasks in #2.)

I was thinking about how I would go about doing layers with Slither and I came up with two solutions:
- Directly re-order the `sprites` list
- Give each sprite a z-index that would be used to sort the `sprites` list

Re-ordering allows us to use "go to front" and "go back () layers" functions, but z-indexes would allow us to quickly sort the `sprites` list.

@BookOwl, @Omegabyte, what do you guys think?

**Comment by ghost** [comment]
Hmm

**Comment by ghost** [comment]
I'm thinking directly reorder the sprite list, adding z-indexes wold just increase complexity.

**Comment by BookOwl** [comment]
I think that we should use z-indexes because
1. It would make it easy for the end user to get the z-index of a Sprite by just using `sprite.zIndex`
2. It would be easy to implement. We would just need to do `sorted(sprites, key=(lambda s: s.zIndex))`

**Comment by ghost** [comment]
true

**Comment by Tymewalk** [comment]
So I think z-indexes are the way to go.
I'll get on that, it shouldn't be too hard.

**Comment by Tymewalk** [comment]
In #31 I added the z-indexes. So I'm closing this since we've reached a conclusion and added it with no problems.
