### ISSUE TITLE
Should we use set and get functions?

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#30]
Take a look at code in the `Sprite` class:

```
def changeScaleBy(self, amount):
    '''Change the sprite's scale by (amount).'''
    self.scale += amount

def setScaleTo(self, scale):
    '''Set the sprite's scale to (amount).'''
    self.scale = scale

def getScale(self):
    '''Get the sprite's current scale.'''
    return self.scale
```

Should we use `set` and `get` functions?

**Comment by BookOwl** [comment]
Since we are not validating anything, I say that we get rid of them and just let the user directly manipulate the variables. If we decide that we need validation, we can always switch to properties.

**Comment by Tymewalk** [comment]
@BookOwl OK.
Should we remove the `changeBy` functions, too? Or should we leave those in?

**Comment by BookOwl** [comment]
Yes

**Comment by Tymewalk** [comment]
@BookOwl OK. I'll get on it.

**Comment by Tymewalk** [comment]
Wait, we actually DO validate something - when the z-index is changed we reorder the sprites.
That's the only thing though.

**Comment by BookOwl** [comment]
We can use properties to automatically reorder the sprites list when it gets changed. I'm on my way home from camping now, I can work on this either tonight or tomorrow. (I'm in the Eastern time zone)

**Comment by Tymewalk** [comment]
@BookOwl OK. Whenever is fine, I'll just make a separate branch so I can get started. :smile:

**Comment by BookOwl** [comment]
Great!

**Comment by Tymewalk** [comment]
Closing as this was only a question, we've reached an agreement.

Discussion about the actual implementation should go in #34.
