### ISSUE TITLE
Split tests and examples

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#32]
I notice we have most of our tests in `examples/`.
I think we should have a separate folder for tests.

**Comment by BookOwl** [comment]
:+1:

**Comment by ghost** [comment]
Working on it, should be done soon.

**Comment by BookOwl** [comment]
We should move the examples directory to the slither folder, so that we can distribute the examples on PyPi with the slither package.

**Comment by Tymewalk** [comment]
@BookOwl OK, then our tests can be in `tests/`?

**Comment by BookOwl** [comment]
That sounds great to me!

**Comment by BookOwl** [comment]
@Omegabyte, how is it coming?

**Comment by ghost** [comment]
I'm getting errors when I try to push the changes, I'm sending from my phone. I should be able to use my computer in a few hours.

**Comment by Tymewalk** [comment]
#46 fixes the moving examples into the `slither/` folder so they can be bundled with Slither when downloading from PyPi.

Now we just need a `tests/` folder for ourselves.

**Comment by ghost** [comment]
Done! I had to reclone the repository and do it again.
