### ISSUE TITLE
Move slither to an organization.

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#37]
This will allow us to have finer-grained control over who has access to what, and allows us to stick multiple repositories under the slither banner, which will come in handy if we decide to write our own svg rasterizer (#35) or create a 3d version.

**Comment by Tymewalk** [comment]
OK. I'll make one now.

**Comment by Tymewalk** [comment]
The name "Slither" is taken. But "SlitherPygame" isn't.

**Comment by BookOwl** [comment]
How about "PySlither"?

**Comment by Tymewalk** [comment]
@BookOwl That's not taken. I like it!
Should I go ahead and create it?

**Comment by BookOwl** [comment]
@Tymewalk sure!

**Comment by BookOwl** [comment]
You then need to go to the settings tab of this repo to move slither to the slither org.

**Comment by Tymewalk** [comment]
@BookOwl OK. It's also saying we need a billing e-mail. What should I put, GitHub's no-reply?

**Comment by BookOwl** [comment]
There should be a free option... Let me look into at the docs real quick.

**Comment by Tymewalk** [comment]
@BookOwl There is a free option, I chose it, but it still wants a billing e-mail.

**Comment by BookOwl** [comment]
@Tymewalk, just put in your email address

**Comment by Tymewalk** [comment]
@BookOwl Done. You've been invited, and so has everyone else!

**Comment by BookOwl** [comment]
Awesome!
