### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#40]
Would be nice

**Comment by Tymewalk** [comment]
After #32 gets completed tutorials can go in there, along with a quick-start guide in the docs.
@PySlither/documentation

**Comment by Tymewalk** [comment]
#32 is done (at least the part that matters is), so now we can start working on this.

**Comment by ghost** [comment]
Quick start guide but no full tutorial... I'll work on this.

**Comment by Tymewalk** [comment]
> Quick start guide but no full tutorial... I'll work on this.

Thanks. :+1: By the way, I updated the main help page if that's useful. :smile:

**Comment by Tymewalk** [comment]
This was pretty much resolved when we got some groundwork done. However, the docs are still not high-quality.

Direct anything else for this thread to #67.
