### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#41]
Github has a service called Github Pages that takes our README and creates a site for us, and hosts it. This might be nice later.

**Comment by Tymewalk** [comment]
I'm aware of GitHub pages, I've used it myself :smile: 
I do like the idea of a website, but I also think that's a little farther down the line.

**Comment by BookOwl** [comment]
The explanation was for people who have never heard of it. :package: 

> I do like the idea of a website, but I also think that's a little farther down the line.

That's why I added the far-future label. :package:

**Comment by Tymewalk** [comment]
> The explanation was for people who have never heard of it.

_facepalms_ Sometimes I forget I'm not the only person here...

**Comment by ghost** [comment]
Who doesn't know what github pages is?

**Comment by ghost** [comment]
I would like to help with this, HTML is fun.

**Comment by ghost** [comment]
This is a bit of a future thing but I'll look into it.

**Comment by BookOwl** [comment]
We could use pages to host our docs, if #71 gets approved

**Comment by BookOwl** [comment]
We are using gh-pages to host our docs
