### ISSUE TITLE
Basic collision detection

### ISSUE THREAD

**Issue by ghost** [Tymewalk/Slither#42]
This would be useful for games

**Comment by BookOwl** [comment]
We can put this in v0.3

**Comment by Tymewalk** [comment]
[This](http://stackoverflow.com/a/9312895) could help, now that we're working on v0.3.0.

**Comment by Tymewalk** [comment]
http://stackoverflow.com/questions/9542555/collide-detection-and-masks-in-python-3-2-2
http://stackoverflow.com/questions/9312781/pygame-collision/9312895#9312895
http://pygame.org/wiki/FastPixelPerfect?parent=

I'd like to work on this, this is a good feature for us to add (perhaps it'd even go in 0.2.3). So here are some helpful links.

**Comment by Tymewalk** [comment]
So @BookOwl said that we should use the `collideRect` method. So I've added the "easy" label.

**Comment by Tymewalk** [comment]
For current progress see #61. This should be closed soon.

**Comment by BookOwl** [comment]
I merged #61. Closing.
