### ISSUE TITLE
Release v0.2

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#44]
Since #9 was (finally!) fixed, I think that we should make a version 0.2 release.

**Comment by BookOwl** [comment]
Tymewalk said that when #36 was finished, we'll release version 0.2

**Comment by Tymewalk** [comment]
So since #36 is done, can anyone else think of anything that should be done before v0.2?

**Comment by BookOwl** [comment]
We should update the examples to the new API and put them in the slither package.

**Comment by Tymewalk** [comment]
That's right, I forgot about #32.

**Comment by Tymewalk** [comment]
Side note - if we really wanted, we could include examples in an 0.2.1 release.

**Comment by BookOwl** [comment]
OK, lets just get #36 done and then release version 0.2

**Comment by Tymewalk** [comment]
#36 is done, and while doing that I checked and didn't find any other problems.
So we're ready to release?

**Comment by BookOwl** [comment]
I think so!

**Comment by Tymewalk** [comment]
Sounds good! I'll build and upload it to PyPi.

**Comment by BookOwl** [comment]
I'll make the Github release

**Comment by BookOwl** [comment]
Since 0.2 has been released, closing
