### ISSUE TITLE
move (n) steps

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#48]
![capture](https://cloud.githubusercontent.com/assets/13385064/14190334/2b1f9dc4-f760-11e5-963d-10f8ff9349ab.PNG)

I can't believe that we don't have this function.

**Comment by ghost** [comment]
LOL! We forgot the easiest thing.

**Comment by Tymewalk** [comment]
Not really "easiest", but it's something.
I believe we could just take the code from Scratch for this block. (Although we'd have to decide how it relates to direction...)

**Comment by BookOwl** [comment]
There is a workaround shown [here](http://wiki.scratch.mit.edu/wiki/Move_%28%29_Steps_%28block%29). We could use it.

**Comment by Tymewalk** [comment]
@BookOwl The workaround looks good to me!

**Comment by BookOwl** [comment]
I added it in pull request #51

**Comment by Tymewalk** [comment]
Closed as I merged that pull request.
