### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by ghost** [Tymewalk/Slither#49]
Sound seems to work fie but the was a comment saying it was't working. hmm?

**Comment by BookOwl** [comment]
When I tried it I just got a bunch of errors

**Comment by Tymewalk** [comment]
I tried it and didn't hear a boom, just "click-click-click-click..."

**Comment by ghost** [comment]
Oh, I'm getting an indent error.

**Comment by ghost** [comment]
It won't go away!!!!!

**Comment by ghost** [comment]
`IndentationError: unindent does not match any outer indentation level`

**Comment by ghost** [comment]
It goes click click click if it cannot find a sound file.

**Comment by BookOwl** [comment]
I always got a pygame exception saying that it could not load the file. I think that we should disable the code in the master branch and make a new branch that we can use to try and get sound to work

**Comment by ghost** [comment]
Wait

**Comment by ghost** [comment]
Ok, I fixed the indent error.

**Comment by ghost** [comment]
Should work now.

**Comment by ghost** [comment]
Yeah I think your right BookOwl, now I'm getting a memory error.

**Comment by ghost** [comment]
Yay, memory error comes up cause my computer doesn't have much ram.

**Comment by emmatyping** [comment]
A memory error? With audio? Hm. That seems strange. To be clear are you getting an out of memory error? Or is it an access violation? or something else?

**Comment by Tymewalk** [comment]
I agree, that is strange. Can you post the exact error?

**Comment by BookOwl** [comment]
Since we're having so much trouble getting Pygame's audio to work, maybe we should try using [simpleaudio](https://pypi.python.org/pypi/simpleaudio/1.0.0)

**Comment by ghost** [comment]
YESSSSS! FInally fixed it! I forgot to initilise the pygame mixer, thats why there was a memory error,
http://stackoverflow.com/questions/8690301/pygame-memoryerror

**Comment by ghost** [comment]
Going to release a patch...
