### ISSUE TITLE
Code of conduct.

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#50]
I think that we need some more rules for how to contribute to slither. Here is what I have so far:
1. Never push directly to master. Always branch and make pull requests. By doing this, we make sure that the code in master is 100% bug free and that any changes get reviewed.
   Exception: If you are just doing a bug fix that really can not wait, you can push directly to master, but this should be quite rare.
2. Only @Tymewalk should merge pull requests that add features.

**Comment by ghost** [comment]
Don't we already have this? See readme.md

**Comment by BookOwl** [comment]
Yes, but I wanted to formalize it to make it easier for other people to contribute.

**Comment by BookOwl** [comment]
@Tymewalk

**Comment by Tymewalk** [comment]
How about this (modifying what you said a little):
1. Never push directly to master. Always make branches and pull requests. This is to make sure Slither stays as bug-free as possible.
   - The only exception is minor changes or important bugfixes that can't wait for someone to review it.
2. Always ask for feedback before merging a pull request.
3. Only @Tymewalk should merge pull request that add features or change large portions of Slither.
4. Make a new issue if you want to propose a new release. Don't make releases without getting approval from other contributors.
5. Have fun!

**Comment by BookOwl** [comment]
@Tymewalk sounds great to me!

**Comment by Tymewalk** [comment]
(So GitHub only auto-closes with `Fix #N`, not `Add #N`?)
Closed because this was added. If anyone would like to propose changes, make a new issue.
