### ISSUE TITLE
Make sprites automatically change to the new costume when adding one

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#52]
Currently, to add a costume to a Sprite and change to it, you have to write the following:

``` python
sprite.addCostume("some_file.png", "some_name")
sprite.costumeName = "some_name"
```

It would be nice if the addCostume method made the sprite switch to the added costume

**Comment by Tymewalk** [comment]
I think @Icelys made a change that auto-swapped to the first added costume. So all we have to do is remove the code to check if it's the first costume.

**Comment by BookOwl** [comment]
Added in pull request #53 (not merged)

**Comment by Tymewalk** [comment]
Merged. Closing this issue.
