### ISSUE TITLE
Live?

### ISSUE THREAD

**Issue by skistaddy** [Tymewalk/Slither#57]
Do you guys have a website? I think it would be useful to have a GH pages website to test.

**Comment by BookOwl** [comment]
1. We talked about making a website in #41, but I think that we decided to wait until version 1.0 to really consider it.
2. This is a python library, I'm not sure how people could test it out on a website...

**Comment by skistaddy** [comment]
Oh. I thought this was like Elemental, except with python blocks.

**Comment by BookOwl** [comment]
No, this is a Python library designed to make it easier to create Scratch style programs with graphics.

**Comment by BookOwl** [comment]
Although a block based python website would be cool...

**Comment by skistaddy** [comment]
Yeah, I agree. I my start on that.... XD

**Comment by emmatyping** [comment]
Somewhat related I guess, I was thinking it would be cool to use [Brython](http://www.brython.info/) and [brython-pygame](https://github.com/brython-dev/brython-pygame) to run Slither in the web (I plan on playing with this when I get the time).

EDIT: also if you couldn't tell I changed my username. :smile:

**Comment by Tymewalk** [comment]
@ethanhs Woah, neat! Didn't know that thing existed for Python.

**Comment by ghost** [comment]
I know right! I've been a bit busy on schoolwork lately, have I missed anything important?

**Comment by ghost** [comment]
Yeah a block based editor would be awesome!
Although it wouldn't be easy to make.

**Comment by skistaddy** [comment]
Should we? I can make an organization and a Scratch Topic...

**Comment by BookOwl** [comment]
> Should we? I can make an organization and a Scratch Topic...

That sounds like a neat project, but I think that it should be separate from Slither.
If you do it, I might join.

**Comment by skistaddy** [comment]
K. I'll start it.

**Comment by skistaddy** [comment]
Made it: https://scratch.mit.edu/discuss/topic/194076/

**Comment by ghost** [comment]
We could eventually join it into slither but for now it's still a test thing.

**Comment by BookOwl** [comment]
This seems out of the scope of what slither is meant to be. Maybe we can look at this some more later, but for now I'm closing.
