### ISSUE TITLE
Old slither on pypi

### ISSUE THREAD

**Issue by ghost** [Tymewalk/Slither#59]
We need to have slither 2.2 (Or whatever the current version is) on pypi. Version 2.1 doesn't have the sound fix and it has an examples folder but no test folder.

**Comment by ghost** [comment]
The current repo is 20 commits ahead.

**Comment by Tymewalk** [comment]
OK. I'll get to work on it, unless anyone can think of anything important in the next 5 minutes.
While we could just hold out until 0.3.0 I think that's a bad idea seeing as how these changes are tested, ready-to-go, and also somewhat important.

Plus the PyPi version hasn't been updated for a month and I kind of want some way for people to know we're still alive :stuck_out_tongue:

**Comment by Tymewalk** [comment]
OK, so it's been a little over 15 minutes.
I'm cloning the repo and getting ready to build and upload.

**Comment by Tymewalk** [comment]
Don't use the one on the PyPi servers now - that's broken due to some error.

**Comment by Tymewalk** [comment]
OK, PyPi is having some trouble. So it'll be a little while. I'll come back and close this when it gets fixed.

**Comment by Tymewalk** [comment]
Upon further investigation only Slither is having trouble?
Trying to bump version to 0.2.3 and then delete the broken packages.

**Comment by Tymewalk** [comment]
OK, so I got into Slither, but now I can't see the releases?!

**Comment by Tymewalk** [comment]
It looks like it's only the releases tab. Sadly that's what I need to get to in order to fix 0.2.2 :frowning:

**Comment by Tymewalk** [comment]
Can't access the releases tab on Tymeventure either.

Anyone know what to do?

**Comment by Tymewalk** [comment]
Well, it got fixed somehow.
But now PyPi doesn't like me uploading 0.2.2 since "that filename has already been used before".

**Comment by Tymewalk** [comment]
Oh. Never mind. It appears to have uploaded it anyway, it must've been just a warning.
