### ISSUE TITLE
Getting keypresses?

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#60]
I think there should be a function to get what keys are pressed in a Slither project.

I know how to go about this, but I'm not sure how it should be structured. What kind of function should we use? How would it be used?

**Comment by skistaddy** [comment]
Well, the syntax could look something like `key.Down('a')`

**Comment by Tymewalk** [comment]
Oh, OK, and then it just returns whether or not that key is being pressed?

**Comment by skistaddy** [comment]
Yeah. True or False.

**Comment by ghost** [comment]
Doesn't the function registerCallback() do this?

**Comment by BookOwl** [comment]
You can already register callbacks for key presses, but a way to get a list of pressed down keys would be good

**Comment by BookOwl** [comment]
I like the function `slither.keysDown()`. It would return a list of the currently held down keys.

**Comment by BookOwl** [comment]
PR #64 adds this.

**Comment by Tymewalk** [comment]
Closing as #64 was merged.
