### ISSUE TITLE
Easy command to blit text?

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#62]
Should we have a command that works like this:

```
blitText("Hello, world!", (0, 0), size=10, font="somefont.ttf")
```

**Comment by BookOwl** [comment]
Yes, but I would prefer something like
`showText(text="Hi!", x=0, y=0, size=12, font="Helvetica")`

**Comment by Tymewalk** [comment]
@BookOwl What about this (mandatory text argument):
`showText("Hello!", x=0, y=0, size=12, font="Helvetica")`

`font` has to be a system font, but you can also specify a custom one with `fontPath`:
`showText("Hello!", x=0, y=0, size=12, fontPath="path/to/font.ttf")`

If both `font` and `fontPath` are specified then `font` is used. Defaults to the pygame system font if neither are defined.

**Comment by BookOwl** [comment]
@Tymewalk sounds good to me.

**Comment by Tymewalk** [comment]
Once #61 gets merged I'll start working on that.

**Comment by ghost** [comment]
Wow, cool.

**Comment by BookOwl** [comment]
Do we want to add this in v0.3.0 or save it for 0.4?

**Comment by Tymewalk** [comment]
@BookOwl 0.3.0 sounds good. It doesn't seem like it'll be too hard, so no sense in putting it off.

My plan is to get as many useful functions and small things as possible in 0.3.x, since then we can work on advanced stuff for 0.4.

**Comment by BookOwl** [comment]
@Tymewalk, are you still planning on doing this?

**Comment by Tymewalk** [comment]
@BookOwl Yeah. Just had some inactivity

**Comment by Tymewalk** [comment]
> Just had some inactivity

Been gone for over a month now, Past Self :neutral_face:

I'll get to work on this though.

**Comment by Tymewalk** [comment]
We apparently forgot about `color` and `antialias` arguments.

Check #77 for my progress on this.

**Comment by Tymewalk** [comment]
<s>The tricky part here is getting the screen to blit to.</s>

<s>We could ask for which screen as an argument but that could be confusing.</s>

Never mind. We have a `slitherStage` variable.

**Comment by Tymewalk** [comment]
It's done, and it also rewrote a little code which makes `blit`ting new things easier in the future.

Soon we shall release 0.2.3 (or 0.3.0)... :grin:
