### ISSUE TITLE
Python 2 compatibility?

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#63]
Will slither be compatible with Python2?

**Comment by ghost** [comment]
Well I'm running python 2 on windows right now, I'm pretty sure it should remain compatibility with python 2, It's still quite popular.

**Comment by BookOwl** [comment]
According to slither/**init**.py, we will support pythons 2 and 3.

**Comment by Tymewalk** [comment]
Just a small note - if we need to drop support for one I'm OK with that. I just put that in there a long long time ago.
