### ISSUE TITLE
Main code in __init__.py?

### ISSUE THREAD

**Issue by CosmicWebServices** [Tymewalk/Slither#68]
Should this happen?

**Comment by skistaddy** [comment]
Probably not, I believe we should probably make a new file with all the code and just execute it in `__init__.py`

**Comment by CosmicWebServices** [comment]
I agree I am not on the team _yet_ but it seems like a bad idea

**Comment by CosmicWebServices** [comment]
Making a pull request

**Comment by CosmicWebServices** [comment]
Made a pull request #69

**Comment by CosmicWebServices** [comment]
I am IcyCoder by the way

**Comment by BookOwl** [comment]
This has been implemented. Closing
