### ISSUE TITLE
Where should we host the docs?

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#73]
If we use readthedocs, 
- we get free hosting (with small ads)
- the hosted docs are automatically kept up to date
- it looks professional
- it might be tricky to get set up

If we use github pages,
- it's simple to setup and change
- we have to update the hosted docs
- it's completely free without ads
- everyone should know how to use it

**Comment by BookOwl** [comment]
I vote for github pages.

**Comment by Tymewalk** [comment]
I vote for GH Pages too.
- It merges right in our GH repo
- Most people know how to use it
- Directing users shouldn't matter, just append the GH-Pages link to the PyPi description
- It has no ads (always a plus for users)

The only downside I see is that we have to update the docs ourselves, but even that's not too big a problem.

**Comment by skistaddy** [comment]
I vote GH pages.

**Comment by BookOwl** [comment]
@Tymewalk @bjskistad, the Slither docs are live at http://pyslither.github.io/

**Comment by Tymewalk** [comment]
Looks good! Thanks!

**Comment by skistaddy** [comment]
Awesome!
