### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by skistaddy** [Tymewalk/Slither#75]
I think it would be helpful for a CI such as [Travis](https://travis-ci.org/), as it would help check Pull Requests for flaws. It will also check recent commits for you too.

**Comment by emmatyping** [comment]
I definitely support this. We should run our tests etc.

**Comment by skistaddy** [comment]
Also, I would be willing to create the YAML file.

**Comment by BookOwl** [comment]
How can we test graphics?

**Comment by skistaddy** [comment]
@BookOwl You wouldn't test the graphics, you would test the code BEHIND the graphics.

**Comment by BookOwl** [comment]
But since all that (most of) the code does is make graphics, how would we test if the code works?

**Comment by skistaddy** [comment]
idk. There's no way to do that. This is just to check for flaws in written code.

**Comment by BookOwl** [comment]
But "our" code that we would be testing just tells pygame to do stuff, which then just draws stuff on the screen, so I don't know how we would test it.

**Comment by Tymewalk** [comment]
I agree with @BookOwl here. Travis would only check for flaws like:

```
hello World = "Hello"
```

If something was wrong graphically (for example, a PR breaks the rotation script), Travis wouldn't catch that.

**Comment by skistaddy** [comment]
I see.

**Comment by Tymewalk** [comment]
Given what I said above I'm closing this issue as it's been resolved. If anyone has other thoughts feel free to re-open this issue.
