### ISSUE TITLE
basicTest.py doesn't work in Python2

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Slither#76]
The circling sprite in the middle has the wrong costume. I did some testing, and it's been that way since commit  db54b1d (or version 0.2.1). I couldn't get 0.2.0 to work in python2.
The test does work in 0.2.1 on python3

**Comment by BookOwl** [comment]
@Tymewalk

**Comment by Tymewalk** [comment]
Very, very strange. I'll take a look.

**Comment by skistaddy** [comment]
_20 days later..._

**Comment by Tymewalk** [comment]
@bjskistad Yeah, it's been inactive for a while. :tongue:

**Comment by skistaddy** [comment]
:P

**Comment by BookOwl** [comment]
_two months later..._

**Comment by Tymewalk** [comment]
@BookOwl Looking now.

**Comment by BookOwl** [comment]
@Tymewalk great

**Comment by Tymewalk** [comment]
Just confirmed this, it should be "SoExcited" when it's actually "snakey".

**Comment by Tymewalk** [comment]
Both `costumeNumber` and `costumeName` don't work, and it's not a problem with the image. Everything's spelled correctly.

**Comment by Tymewalk** [comment]
Adding some `print`s, it looks like the setter isn't getting called at all.

**Comment by BookOwl** [comment]
I bet that Python2 treats properties differently then Python3

**Comment by Tymewalk** [comment]
@BookOwl Yep.

> Inherit from `Object` - otherwise the setter doesn't work

[source](http://sw32.com/python-2-x-how-to-use-property-settter-and-getter/)

So we'll have to try inheriting from `Object` rather than `Stage`.

**Comment by Tymewalk** [comment]
OH - additionally, it may be clashing with the method name.

So we just preface the variables with underscores.

**Comment by BookOwl** [comment]
If we make `Stage` inherit from `object` we should be good.

**Comment by Tymewalk** [comment]
@BookOwl Yep. Testing now.
