### ISSUE TITLE
Change screen size/fullscreen/caption

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#79]
We should allow users to change these. For example, some users may want widescreen Slither projects, or an automatically updating caption.
- [x] Add a `setCaption` function
- [x] Allow users to set the size of the stage
- [x] Allow full screen

**Comment by BookOwl** [comment]
This sounds like a good idea to me.

**Comment by Tymewalk** [comment]
Clarified title and tags since we're now implementing this.

**Comment by BookOwl** [comment]
~~Should this be a free standing function or a method on `Stage`?~~ I decided on a free function

**Comment by BookOwl** [comment]
Since I finished adding SVG support (#83) , I'll finish up these.

**Comment by Tymewalk** [comment]
PRs were merged, so closing now.
