### ISSUE TITLE
Sprites can't be deleted

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#8]
You can't delete sprites once they've been made, meaning a clone-like feature would be useless.
There's probably a simple fix for this but I'm adding it here so I know that this has to be done.

**Comment by Tymewalk** [comment]
Yes there is - just remove the sprite from the list `sprites`.
The variable is still there, but you can always reassign that variable.

**Comment by Tymewalk** [comment]
If anyone thinks that the fix isn't good, comment here and I'll re-open it.

**Comment by BookOwl** [comment]
Sprites should have a `delete` method that deletes them from the sprite list. It would just be

``` python
def delete(self):
    sprites.remove(self)
```

So that I can do `mySprite.delete()` instead of `slither.sprites.remove(mySprite)`

**Comment by Tymewalk** [comment]
@BookOwl It's done.
