### ISSUE TITLE
Rotating makes it "bounce"

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Slither#9]
Take a look at SoExcited in basicTest.py, or Snakey in turnAndMove.py. They kind of "bounce" while they rotate.

I'll look for some code to fix this...

**Comment by Tymewalk** [comment]
What? No, I didn't close it.

**Comment by Tymewalk** [comment]
It still bounces. Maybe it's the image?
I'll find an image to test that's a perfect circle.

**Comment by Tymewalk** [comment]
This isn't too important, but I do have to test it.

**Comment by BookOwl** [comment]
I created a test for it in 1a50389434a66c7b69ddb79b4c800656c9975ae1 using a circle image. It still happens.

**Comment by Tymewalk** [comment]
@BookOwl That's really strange.
I'll have to find/make a function to rotate around the center rather than the corner...

**Comment by BookOwl** [comment]
I updated the test, and it shows that the problem is in the rotation function

**Comment by Tymewalk** [comment]
OK.
I'll work on #36 so we can merge that and not have to worry about Git's stupid "merge conflicts" when we fix this.

**Comment by BookOwl** [comment]
I figured out what the bug is! I'm working on it now. (it is not the `rotateCenter()` function after all)

**Comment by BookOwl** [comment]
I fixed the bouncing bug... but now the sprites grow and shrink!?!

**Comment by BookOwl** [comment]
I fixed this!!!
